name: fdr
channels:
  - https://www.idiap.ch/software/bob/conda
  - defaults
  - http://www.idiap.ch/software/bob/conda
dependencies:
  - numpy
  - bob.measure
  - scipy
  - matplotlib
  - ipywidgets
  - ipympl
  - jupyterlab_launcher>=0.5.0
  - tensorflow > 2.0
  - scikit-learn
